### ISSUE TITLE
Can this package be used as an external access interface to reviews?

### ISSUE THREAD

**Issue by frederico-klein** [rayyansys/pyworker#1]
Hi All, 

I was wondering if this package was ever intended to be used as an API for a rayyan survey. 

I am entirely new to your system, but my use case is that I wanted to be able to get the latest state of an ongoing survey and export it without needing to use the web interface and click export. 

Is this what this package is meant to do, or is this mostly an in-house thing? 

Also, is the postgresql server accessible for direct connection? If so, is this safe? Does it have like a read-only mode so I can make sure nothing bad happens?

**Comment by hammady** [comment]
Hi @frederico-klein. Thanks for reaching out!
This package is used internally by Rayyan and is not intended for live data access.
Please send an email to rayyan@qcri.org explaining your use case in more detail so that the team can help you better. There are ways to get data out of Rayyan like the Rayyan API, but it needs some scripting.

**Comment by frederico-klein** [comment]
Can you provide a link to the Rayyan API?

**Comment by hammady** [comment]
It is currently in closed preview, but I believe the team can help you once they understand your needs. The Rayyan mobile app already uses Rayyan API and can be found [here](https://github.com/rayyanqcri/rayyan-mobile/blob/master/www/js/services/rayyan.remote.service.js).

**Comment by frederico-klein** [comment]
Hmm, is this a rest api? I am not good with web stuff. 

I would be nice to have a simple python script wrapper. I am not sure how much time I can put into this to learn how to make one myself. 

It is maybe a nice feature request? I will send an email as you suggested. 

Thank you anyway!
